# Generated by Django 5.2.6 on 2025-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='Terms',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
