# Generated by Django 5.2.6 on 2025-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_login_terms_alter_login_email_alter_login_lastname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.AlterField(
            model_name='login',
            name='Email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='Terms',
            field=models.BooleanField(default=False),
        ),
    ]
