# Generated by Django 5.2.6 on 2025-09-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='firstname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Terms',
        ),
        migrations.RemoveField(
            model_name='login',
            name='lastname',
        ),
    ]
