# Generated by Django 5.2.6 on 2025-10-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_item_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='username',
            new_name='user',
        ),
    ]
