# Generated by Django 5.2.6 on 2025-10-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_username_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
