# Generated by Django 5.2.6 on 2025-10-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_item_price_alter_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='itemimage.jpg/', upload_to='product_image/'),
        ),
    ]
