# Generated by Django 5.2.6 on 2025-10-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_item_app_item_user_id_b1c2d1_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='itemimage.jpg', upload_to='product_image'),
        ),
    ]
