# Generated by Django 5.2.6 on 2025-10-13 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_item_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
    ]
