# Generated by Django 5.2.6 on 2025-10-13 08:48

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_item_deleted_at_remove_item_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='deleted',
            new_name='is_deleted',
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            # use timezone.now as a callable default for existing rows
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
