# Generated by Django 5.2.6 on 2025-10-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_deleted_item_is_deleted_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='itemimage.jpg', null=True, upload_to='product_image'),
        ),
    ]
